#!/usr/bin/env python3
"""Keeps the pack metadata files in sync with disk: capability_index.json,
suite_hashes.json, manifest.json, stats.json, golden_selftest.json,
preservation_receipt.json, quality_report.json and SHA256SUMS.txt (capability
data files only, verifiable with `shasum -c`). validation_status.json is
audited but only regenerated by `make validate`, since it attests a real run.

Default: reports drift (missing entries, stale entries, wrong aggregates).
--fix:   appends missing entries and recomputes derived aggregates/hashes.

Conventions (derived from the pre-existing files):
- capability_index.json: one entry per requests/<slug>.jsonl; new entries get
  source "v3-preserved", cases = request line count.
- suite_hashes.json: sha256/bytes per suite for requests/responses/metadata.
- manifest.json: capabilities map (cases + file paths) plus aggregate fields;
  v3/v5 aggregates are derived from capability_index sources, gpqa excluded.
- stats.json: per-capability question-type counts from metadata "type" fields
  (every metadata line must carry "type"; multiple-choice gpqa uses "choice").
"""
import atexit
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

from gpqa_zip import cleanup_unlocked, unlock_paths

ROOT = Path(__file__).resolve().parent.parent
KINDS = ("requests", "responses", "metadata")

# gated capability files (gpqa_diamond) exist only as password-protected zips at
# rest; decrypt them for this run so globs/line-counts/hashes see the data, then
# remove/re-encrypt the plaintext copies at exit
atexit.register(cleanup_unlocked, unlock_paths(
    [ROOT / e[k]
     for e in json.loads((ROOT / 'manifest.json').read_text())['capabilities'].values()
     for k in KINDS]))
CANONICAL_TYPES = ("choice", "noul", "score")


def sha_entry(path: Path) -> dict:
    data = path.read_bytes()
    return {"path": path.relative_to(ROOT).as_posix(), "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)}


def load(name: str):
    return json.loads((ROOT / name).read_text())


index_path = ROOT / "capability_index.json"
hashes_path = ROOT / "suite_hashes.json"
manifest_path = ROOT / "manifest.json"
stats_path = ROOT / "stats.json"

index = load("capability_index.json")
hashes = load("suite_hashes.json")
manifest = load("manifest.json")
stats = load("stats.json")
selftest = load("golden_selftest.json")
preservation = load("preservation_receipt.json")
quality = load("quality_report.json")
validation = load("validation_status.json")

request_slugs = {p.stem for p in (ROOT / "requests").glob("*.jsonl")}
index_slugs = {e["slug"] for e in index}
caps = manifest["capabilities"]

# derived aggregates, keyed like manifest/stats so both can be checked/updated
cases_by_slug = {e["slug"]: e["cases"] for e in index}
source_by_slug = {e["slug"]: e["source"] for e in index}
v3_slugs = [s for s, src in source_by_slug.items() if src == "v3-preserved"]
v5_slugs = [s for s, src in source_by_slug.items() if src == "v5-capability-spec"]
stats_slugs = sorted(request_slugs)

aggregates = {
    "total_cases": sum(cases_by_slug[s] for s in stats_slugs),
    "total_capabilities": len(stats_slugs),
    "existing_v3_cases": sum(cases_by_slug[s] for s in v3_slugs),
    "new_v5_suites": len(v5_slugs),
    "new_v5_cases": sum(cases_by_slug[s] for s in v5_slugs),
}


def type_counts(slug: str) -> Counter:
    counts = Counter()
    meta = ROOT / "metadata" / f"{slug}.jsonl"
    if meta.exists():
        counts.update(t for line in meta.read_text().splitlines() if (t := json.loads(line).get("type")))
    return counts


def report(name: str, expected: dict, actual: dict) -> list[str]:
    drift = [f"{k}: {actual.get(k)!r} -> {expected[k]!r}" for k in expected if actual.get(k) != expected[k]]
    print(f"{name} drift ({len(drift)}): {drift or 'none'}")
    return drift


legacy_entries = [s for s, v in caps.items() if "request_file" in v]
missing_in_index = sorted(request_slugs - index_slugs)
missing_in_hashes = sorted(request_slugs - hashes.keys())
missing_in_manifest = sorted(request_slugs - caps.keys())
stale_anywhere = sorted(index_slugs - request_slugs)

print(f"index: {len(index)}, hashes: {len(hashes)}, manifest caps: {len(caps)}, request files: {len(request_slugs)}")
print(f"missing in index ({len(missing_in_index)}): {missing_in_index or 'none'}")
print(f"missing in hashes ({len(missing_in_hashes)}): {missing_in_hashes or 'none'}")
print(f"missing in manifest ({len(missing_in_manifest)}): {missing_in_manifest or 'none'}")
print(f"stale (index slug without request file) ({len(stale_anywhere)}): {stale_anywhere or 'none'}")
print(f"legacy manifest entries (request_file naming) ({len(legacy_entries)}): {legacy_entries or 'none'}")
report("manifest aggregates", {k: aggregates[k] for k in aggregates if k in manifest}, manifest)

stats_expected = {
    "total_cases": aggregates["total_cases"],
    "total_capabilities": aggregates["total_capabilities"],
    "existing_v3_capabilities": len(v3_slugs),
    "existing_v3_cases": aggregates["existing_v3_cases"],
    "new_v5_capabilities": len(v5_slugs),
    "new_v5_cases": aggregates["new_v5_cases"],
    "cases_per_capability": Counter(cases_by_slug.values()).most_common(1)[0][0],
}
report("stats aggregates", stats_expected, stats)
stats_missing_caps = sorted(set(stats_slugs) - stats["per_capability_types"].keys())
print(f"stats per_capability missing ({len(stats_missing_caps)}): {stats_missing_caps or 'none'}")

selftest_missing = sorted(request_slugs - selftest.keys())
print(f"golden_selftest missing ({len(selftest_missing)}): {selftest_missing or 'none'}")

# preservation: v5_sha256 must match current file contents
preservation_drift = [f["path"] for f in preservation["files"]
                      if hashlib.sha256((ROOT / f["path"]).read_bytes()).hexdigest() != f["v5_sha256"]]
print(f"preservation sha drift ({len(preservation_drift)}): {preservation_drift or 'none'}")

def expected_sums() -> list[str]:
    """/ shasum-format lines for every capability data file (requests/golden/metadata)."""
    lines = []
    for d in KINDS:
        for p in sorted((ROOT / d).glob("*.jsonl")):
            lines.append(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(ROOT).as_posix()}")
    return sorted(lines)


quality_expected = {
    "cases": aggregates["total_cases"],
    "capabilities": aggregates["total_capabilities"],
    "cases_per_capability": stats_expected["cases_per_capability"],
    "new_v5_suites": aggregates["new_v5_suites"],
    "new_v5_cases": aggregates["new_v5_cases"],
    "existing_v3_jsonl_files_checked": len(preservation["files"]),
    "existing_v3_jsonl_files_byte_identical": sum(1 for f in preservation["files"] if f["identical"]),
}
report("quality_report counts", quality_expected, quality)
report("validation_status", {"cases": aggregates["total_cases"], "capabilities": aggregates["total_capabilities"]}, validation)

sums_path = ROOT / "SHA256SUMS.txt"
expected = expected_sums()
actual_sums = sums_path.read_text().splitlines() if sums_path.exists() else []
sums_drift = "drift" if actual_sums != expected else "none"
print(f"SHA256SUMS drift: {sums_drift} (expected {len(expected)} lines, have {len(actual_sums)})")

if "--fix" in sys.argv:
    if missing_in_index:
        for slug in missing_in_index:
            cases = len((ROOT / "requests" / f"{slug}.jsonl").read_text().splitlines())
            index.append({
                "slug": slug,
                "title": slug.replace("_", " "),
                "source": "v3-preserved",
                "cases": cases,
            })
        index_path.write_text(json.dumps(index, indent=2) + "\n")
        print(f"added {len(missing_in_index)} entries -> {index_path.name}")

    for slug in list(hashes) + missing_in_hashes:
        hashes[slug] = {
            kind: sha_entry(path)
            for kind in KINDS
            if (path := ROOT / kind / f"{slug}.jsonl").exists()
        }
    hashes_path.write_text(json.dumps(hashes, indent=2) + "\n")
    print(f"wrote {len(hashes)} entries -> {hashes_path.name}")

    for slug in legacy_entries:
        old = caps[slug]
        caps[slug] = {
            "cases": old["cases"],
            "requests": old["request_file"],
            "responses": old["golden_response_file"],
            "metadata": old["metadata_file"],
        }
    if legacy_entries:
        print(f"normalized {len(legacy_entries)} legacy entries -> {manifest_path.name}")
    if missing_in_manifest:
        for slug in missing_in_manifest:
            caps[slug] = {
                "cases": cases_by_slug[slug],
                **{kind: f"{kind}/{slug}.jsonl" for kind in KINDS if (ROOT / kind / f"{slug}.jsonl").exists()},
            }
        print(f"added {len(missing_in_manifest)} capabilities -> {manifest_path.name}")
    for k, v in aggregates.items():
        if k in manifest:
            manifest[k] = v
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote aggregates -> {manifest_path.name}")

    per_cap = stats["per_capability_types"]
    for slug in list(per_cap) + stats_missing_caps:
        counts = type_counts(slug)
        per_cap[slug] = {t: counts.get(t, 0) for t in CANONICAL_TYPES}
    # drop entries that moved out of v3+v5 scope (e.g. re-sourced suites)
    for slug in list(per_cap):
        if slug not in stats_slugs:
            del per_cap[slug]
    totals = Counter()
    for entry in per_cap.values():
        totals.update(entry)
    stats["question_types"] = {t: totals.get(t, 0) for t in CANONICAL_TYPES}
    stats.update(stats_expected)
    stats_path.write_text(json.dumps(stats, indent=2) + "\n")
    print(f"wrote {len(per_cap)} per-capability types -> {stats_path.name}")

    # golden_selftest: golden-vs-golden is structurally perfect (identical
    # prediction/gold functions), so entries derive from case counts + types
    for slug in list(selftest) + selftest_missing:
        if slug == "micro":
            continue
        has_score = type_counts(slug).get("score", 0) > 0
        selftest[slug] = {"n": cases_by_slug[slug], "accuracy": 1.0, "score_mae": 0.0 if has_score else None}
    selftest.pop("micro", None)
    selftest["micro"] = {"n": aggregates["total_cases"], "accuracy": 1.0}
    (ROOT / "golden_selftest.json").write_text(json.dumps(selftest, indent=2) + "\n")
    print(f"wrote {len(selftest)} entries -> golden_selftest.json")

    for f in preservation["files"]:
        cur = hashlib.sha256((ROOT / f["path"]).read_bytes()).hexdigest()
        f["v5_sha256"] = cur
        f["identical"] = cur == f["v3_sha256"]
    preservation["checked_files"] = len(preservation["files"])
    preservation["byte_identical"] = all(f["identical"] for f in preservation["files"])
    (ROOT / "preservation_receipt.json").write_text(json.dumps(preservation, indent=2) + "\n")
    print(f"wrote {len(preservation['files'])} files -> preservation_receipt.json (byte_identical={preservation['byte_identical']})")

    sums_path.write_text("".join(line + "\n" for line in expected))
    print(f"wrote {len(expected)} checksums -> SHA256SUMS.txt")

    # recompute after preservation refresh so the byte-identical count is current
    quality_expected["existing_v3_jsonl_files_byte_identical"] = sum(1 for f in preservation["files"] if f["identical"])
    quality.update(quality_expected)
    (ROOT / "quality_report.json").write_text(json.dumps(quality, indent=2) + "\n")
    print(f"wrote counts -> quality_report.json")
